### ISSUE TITLE
integrate mongo with the app

### ISSUE THREAD

**Issue by SuyogSoti** [keatonjwhitehead/L1_Cashe#3]

**Comment by jasonlubrano** [comment]
https://docs.mongodb.com/stitch/examples/mongodb-android/

**Comment by jasonlubrano** [comment]
https://docs.mongodb.com/ecosystem/tools/

**Comment by jasonlubrano** [comment]
For web apps: https://docs.mongodb.com/stitch/examples/mongodb-javascript/
For android apps: https://docs.mongodb.com/stitch/examples/mongodb-android/
General tools: https://docs.mongodb.com/ecosystem/tools/

MongoDB Code school: https://www.codeschool.com/courses/the-magical-marvels-of-mongodb
